export const LabelFieldMap = {
  PACKAGE_LABEL: {
    label: "Package Label",
    fields: [
      { id: "product_name", label: "Product Name" },
      { id: "strain_name", label: "Strain Name" },
      { id: "store_name", label: "Store Name" },
      { id: "store_license", label: "Store License" },
      { id: "net_weight", label: "Net Weight" },
      { id: "mj_weight", label: "MJ Weight" },
      { id: "origin_id", label: "Origin ID" },
      { id: "sku", label: "SKU" },
      { id: "sku_barcode", label: "SKU Barcode" },
      { id: "batch_id", label: "Batch ID" },
      { id: "harvest_date", label: "Harvest Date" },
      { id: "manufacture_date", label: "Manufacture Date" },
      { id: "supplier_name", label: "Supplier Name" },
      { id: "supplier_license", label: "Supplier License" },
      { id: "test_results", label: "Test Results" },
      { id: "test_results_qr", label: "Test Results QR", custom: true },
      { id: "total_terpenes", label: "Total Responses" },
      { id: "product_category", label: "Product Category" },
      { id: "product_price", label: "Product Price" },
      { id: "expiration_date", label: "Expiration Date" },
      { id: "package_text", label: "Package Text" },
      { id: "package_barcode", label: "Package Barcode", custom: true },
    ],
    margins: {
      top: "0.05in",
      right: "0.05in",
      bottom: "0.05in",
      left: "0.05in",
    },
    dimensions: {
      width: "2in",
      height: "1.2in",
    },
  },
  EXIT_LABEL: {
    label: "Exit Label",
    fields: [
      { id: "product_name", label: "Product Name" },
      { id: "order_date", label: "Order Date" },
      { id: "patient_name", label: "OrderName" },
      { id: "patient_license", label: "Patient License" },
      { id: "strain_name", label: "Strain Name" },
      { id: "store_name", label: "Store Name" },
      { id: "store_license", label: "Store License" },
      { id: "net_weight", label: "Net Weight" },
      { id: "mj_weight", label: "MJ Weight" },
      { id: "origin_id", label: "Origin ID" },
      { id: "sku", label: "SKU" },
      { id: "package_id", label: "Package ID" },
      { id: "batch_id", label: "Batch ID" },
      { id: "harvest_date", label: "Harvest Date" },
      { id: "manufacture_date", label: "Manufacture Date" },
      { id: "supplier_name", label: "Supplier Name" },
      { id: "supplier_license", label: "Supplier License" },
      { id: "test_results", label: "Test Results" },
      { id: "test_results_qr", label: "Test Results QR", custom: true },
      { id: "total_terpenes", label: "Total Responses" },
      { id: "product_category", label: "Product Category" },
      { id: "product_price", label: "Product Price" },
      { id: "expiration_date", label: "Expiration Date" },
    ],
    margins: {
      top: "0.1in",
      right: "0.1in",
      bottom: "0.1in",
      left: "0.1in",
    },
    dimensions: {
      width: "2.25in",
      height: "4in",
    },
  },
  RECEIPT: {
    label: "Receipt",
    fields: [
      { id: "company_logo", label: "Company Logo", custom: true },
      { id: "print_date", label: "Print Date" },
      { id: "store_id", label: "Store ID" },
      { id: "order_id", label: "Order ID" },
      { id: "store_name", label: "Store Name", custom: true },
      { id: "store_address", label: "Store Address", custom: true },
      { id: "store_phone", label: "Store Phone", custom: true },
      { id: "store_website", label: "Store Website", custom: true },
      { id: "store_email", label: "Store Email", custom: true },
      { id: "batch_id", label: "Batch ID" },
      { id: "budtender", label: "Budtender" },
      { id: "budtenderId", label: "Budtender ID" },
      { id: "return_reason", label: "Return Reason" },
      { id: "customer_name", label: "Customer Name" },
      { id: "customer_type", label: "Customer Type" },
      { id: "customer_id", label: "Customer ID" },
      { id: "loyalty_points_earned", label: "Current Loyalty Points Earned" },
      { id: "excise_tax_notification", label: "Excise Tax Notification", custom: true },
      { id: "order_contents", label: "Order Contents", custom: true },
      { id: "order_barcode", label: "Order Barcode", custom: true },
    ],
    margins: {
      top: "0.1in",
      right: "0.1in",
      bottom: "0.1in",
      left: "0.1in",
    },
    dimensions: {
      width: "2.25in",
      height: "8in",
    },
  },
  DELIVERY_RECEIPT: {
    label: "Delivery Receipt",
    fields: [
      { id: "company_logo", label: "Company Logo", custom: true },
      { id: "print_date", label: "Print Date" },
      { id: "store_id", label: "Store ID" },
      { id: "order_id", label: "Order ID" },
      { id: "store_name", label: "Store Name", custom: true },
      { id: "store_address", label: "Store Address", custom: true },
      { id: "store_phone", label: "Store Phone", custom: true },
      { id: "store_website", label: "Store Website", custom: true },
      { id: "store_email", label: "Store Email", custom: true },
      { id: "batch_id", label: "Batch ID" },
      { id: "budtender", label: "Budtender" },
      { id: "budtenderId", label: "Budtender ID" },
      { id: "return_reason", label: "Return Reason" },
      { id: "customer_name", label: "Customer Name" },
      { id: "customer_type", label: "Customer Type" },
      { id: "customer_id", label: "Customer ID" },
      { id: "loyalty_points_earned", label: "Current Loyalty Points Earned" },
      { id: "excise_tax_notification", label: "Excise Tax Notification", custom: true },
      { id: "order_contents", label: "Order Contents", custom: true },
      { id: "order_barcode", label: "Order Barcode", custom: true },
    ],
    margins: {
      top: "0.1in",
      right: "0.1in",
      bottom: "0.1in",
      left: "0.1in",
    },
    dimensions: {
      width: "2.25in",
      height: "8in",
    },
  },
  PRE_ORDER_FULFILLMENT_PULL_SHEET: {
    label: "Pre-Order Fulfillment Pull Sheet",
    fields: [
      { id: "store_name", label: "Store Name" },
      { id: "order_time", label: "Order Time", custom: true },
      { id: "order_contents", label: "Order Contents", custom: true },
      { id: "customer_name", label: "Customer Name" },
      { id: "customer_phone", label: "Customer Phone" },
      { id: "delivery_address", label: "Delivery Address" },
      { id: "preorder_notes", label: "PreOrder Notes" },
      { id: "company_logo", label: "Company Logo", custom: true },
      { id: "order_barcode", label: "Order Barcode", custom: true }
    ],
    margins: {
      top: "0.1in",
      right: "0.1in",
      bottom: "0.1in",
      left: "0.1in",
    },
    dimensions: {
      width: "2.25in",
      height: "8in",
    },
  },
};
